### ISSUE TITLE
cant compile

### ISSUE THREAD

**Issue by Alpdrucken** [longlostsoul/EvoYellow#4]
I installed all the packages for cygwin, but when i try to run "make" i get this:

```
python: can't open file 'extras/pokemontools/scan_includes.py': [Errno 2] No such file or directory
python: can't open file 'extras/pokemontools/scan_includes.py': [Errno 2] No such file or directory
python: can't open file 'extras/pokemontools/scan_includes.py': [Errno 2] No such file or directory
python: can't open file 'extras/pokemontools/scan_includes.py': [Errno 2] No such file or directory
rgbasm -h -o audio.o audio.asm
warning: audio.asm(21): [-Wobsolete]
    `GLOBAL` is a deprecated synonym for `EXPORT`
warning: audio.asm(22): [-Wobsolete]
    `GLOBAL` is a deprecated synonym for `EXPORT`
warning: audio.asm(23): [-Wobsolete]
    `GLOBAL` is a deprecated synonym for `EXPORT`
warning: audio.asm(489) -> audio/engine_1.asm(678): [-Wobsolete]
    Non-local labels without a colon are deprecated
FATAL: audio.asm(670):
Error opening INCBIN file 'gfx/surfing_pikachu_1a.2bpp': No such file or dir
ectory
make: *** [Makefile:42: audio.o] Error 1

```

Also the latest ips patch appears to give an error with every rom I tried.

**Comment by Alpdrucken** [comment]
This is what I get with the extras folder added:

```
Traceback (most recent call last):
  File "extras/pokemontools/scan_includes.py", line 43, in <module>
    main()
  File "extras/pokemontools/scan_includes.py", line 39, in main
    scan_file(filename)
  File "extras/pokemontools/scan_includes.py", line 26, in scan_file
    scan_file(include)
  File "extras/pokemontools/scan_includes.py", line 26, in scan_file
    scan_file(include)
  File "extras/pokemontools/scan_includes.py", line 15, in scan_file
    for line in open(filename):
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x97 in position 4511: invalid start byte
  File "extras/pokemontools/pcm.py", line 113
    raise Exception, "Unsupported sample width: " + str(sample_width)
                   ^
SyntaxError: invalid syntax
make: *** [Makefile:56: audio/pikachu_cries/pikachu_cry_14.pcm] Error 1
```

**Comment by Alpdrucken** [comment]
Managed to compile. Had to download the "extra" folder, downgrade rgbds to 0.2.5 and installed python27-pip on cygwin.
